name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: [ "main" ]   # 👈 Runs when you push to main branch
  workflow_dispatch:        # 👈 Allows you to run manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the project
      - name: Build Vite project
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
